### ISSUE TITLE
Add support for per-kernel chrome tracing equivalent to ChromePerformanceTimingPerKernel in OpenCL-intercept-layer

### ISSUE THREAD

**Issue by nsdhaman** [intel/pti-gpu#10]
Currently, both cl_tracer and ze_tracer support chrome tracing. Can you please enable support similar to ChromePerformanceTimingPerKernel option in OpenCL-intercept-layer (https://github.com/intel/opencl-intercept-layer/blob/master/docs/controls.md#chromeperformancetimingperkernel-bool)? This sets tid value for each device entry to the kernel name. This view (one row per kernel in Chrome trace viewer) can be beneficial for app developers. .

**Comment by anton-v-gorshkov** [comment]
Done. Please verify if this is what you need.

**Comment by nsdhaman** [comment]
Hi Anton, thank you very much. This is what I requested. 
One suggestion for improvement is allowing both --chrome-device-stages and --chrome-kernel-timeline to be specified simultaneously. This allows the cleaner view (one row per kernel) with the stages information for each kernel launch. This is supported in the OCL intercept layer (by setting both CLI_ChromePerformanceTimingInStages=1 and CLI_ChromePerformanceTimingPerKernel=1).  
Thank you again!

**Comment by anton-v-gorshkov** [comment]
Hi Nitin, I've added this mixed mode in newest version, please try it out.

**Comment by nsdhaman** [comment]
Hi Anton,
Great! This works as expected. Thank you very much. 
Closing the issue now.
Nitin.
