### ISSUE TITLE
[feature request]Any way to know memcpy is D2H, H2D or D2D?

### ISSUE THREAD

**Issue by GHGmc2** [intel/pti-gpu#11]
When using ze_tracer with flag `--chrome-device-stages`, we can get the commands named "zeCommandListAppendMemoryCopy", but we cannot figure out whether it's D2H, H2D or D2D memcpy.

Can ze_tracer distinguish these three kinds of memcpy? Thanks!

**Comment by anton-v-gorshkov** [comment]
Hi @GHGmc2,  thanks for this feature request!
Level Zero API by itself doesn't distinguish memory transfer direction that's why ze_tracer doesn't provide this info. But your request is reasonable, so let us try to figure out how we can make it.

**Comment by GHGmc2** [comment]
@anton-v-gorshkov Thanks for your support!

I found that Vtune can figure out the data transfer direction, and GPU pointer address are follow "0xffffd" style:
- code
```c++
#include "CL/sycl.hpp"

constexpr int ALIGN = 64;
constexpr int SIZE = 256;

int main() {
  void *dst = nullptr;
  posix_memalign(&dst, ALIGN, SIZE);

  sycl::queue q(sycl::gpu_selector{}, sycl::property::queue::in_order());
  void *h = sycl::aligned_alloc_host(ALIGN, SIZE, q);
  void *d = sycl::aligned_alloc_device(ALIGN, SIZE, q);

  printf("system host ptr address: %p\n", dst);
  printf("sycl host ptr address: %p\n", h);
  printf("sycl device ptr address: %p\n", d);

  std::free(dst);
  sycl::free(h, q);
  sycl::free(d, q);

  return 0;
}
```

- output
```
system host ptr address: 0x14c4dc0
sycl host ptr address: 0x7fb371b76000
sycl device ptr address: 0xffffd556aa7e0000
```

Maybe it can help to distinct different memcpy.

**Comment by anton-v-gorshkov** [comment]
Right, looks like it should be easy enough. I've found the following function in Level Zero that should give us all needed information - [zeMemGetAllocProperties](https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=zememgetallocproperties#_CPPv423zeMemGetAllocProperties19ze_context_handle_tPKvP33ze_memory_allocation_properties_tP18ze_device_handle_t). So let me just try it out and make a code for you.

**Comment by GHGmc2** [comment]
That wouldn't be better if we can query from official L0 APIs, looking forward to the feature!

**Comment by anton-v-gorshkov** [comment]
Added basic support for memory transfer directions for Level Zero, please, verify if this is what you need.
There types of memory were added:
- "H", host - means system host memory allocated with C malloc or C++ new;
- "D", device - device memory allocated with sycl::malloc_device;
- "S", shared - shared memory allocated with sycl::malloc_host or sycl::malloc_shared (since both will give shared memory accessible both from host and from device).
