### ISSUE TITLE
unitrace fails with: Assertion `zeEventQueryStatus(event) == ZE_RESULT_NOT_READY' failed.

### ISSUE THREAD

**Issue by roysmoore** [intel/pti-gpu#38]
Testing unitrace with ze_peak:

ze_peak: a760ae0b52497b73254b2df8b191aa3693a970c7 (pulled 2023.5.13)

unitrace --version
0.50.0 (b785677885e062c41405fb8d10812f7e7c0c58d9)

 unitrace -h -d -v --chrome-call-logging --chrome-device-logging --chrome-kernel-logging ./ze_peak -t dp_compute

Device :
 * name : Intel(R) Data Center GPU Max 1550
 * vendorId : 8086
 * deviceId : 0bd6
 * subdeviceId : 0
 * isSubdevice : FALSE
 * UUID : 00000000-0000-0000-76d4-156c1ee6653b
 * coreClockRate : 1600

Double Precision Compute (GFLOPS)
double : 32644.5 GFLOPS
ze_peak: /nfs/pdx/home/roymoore/GIT/performance.platform.pti-builds/src/pti-gpu/tools/unitrace/src/levelzero/ze_event_cache.h:105: ze_event_handle_t ZeEventCache::GetEvent(ze_context_handle_t): Assertion `zeEventQueryStatus(event) == ZE_RESULT_NOT_READY' failed.
Aborted (core dumped)

System:
- OS Name      : openSUSE Leap
- OS Version   : 15.3
- Kernel       : 5.3.18-150300.59.98-default
- KMD RPM      : intel-i915-dkms-1.23.3.19.230125.14
- KMD Version  : backported to 5.3.18-150300.59.98 from (I915-23.3.6-23-g44490ef1939be1) using backports SLES15_SP3_23.3.19_PSB_230125.14
- KMD Options  : [ enable_hangcheck=N ]
- Boot Options : [ splash=no net.ifnames=0 quiet linux crashkernel=512M,high crashkernel=256M,low mitigations=off initcall_blacklist=sync_debugfs_init,dma_buf_init,init_tis modprobe.blacklist=ast pcie_ports=native i915.enable_hangcheck=0 pci=pcie_bus_perf ]

- UMD Version  : neo/agama-devel-sp3/644-23.13.26032.30-644
- dpcpp        : 2023.2.0 (2023.x.0.20230514)

**Comment by zma2** [comment]
@roysmoore Can you please try with the latest unitrace? Does it fail only with ze_peak or does it fail with other applications also?

**Comment by roysmoore** [comment]
Running with a current version of unitrace using oneAPI 2024.1, this is no longer an issue.
