### ISSUE TITLE
[WARNING] Unable to decode kernel binary 

### ISSUE THREAD

**Issue by zjin-lcf** [intel/pti-gpu#4]
I followed the build instruction, but running cl_debug_info always shows the message.  However, the gpu_instruction_count test can display the assembly of an application.  This seems generic, so a specific application is not listed.  Any suggestions ?

Thanks

**Comment by anton-v-gorshkov** [comment]
Hi, sorry for long answer - looks like github doesn't send us any notifications on new issues.
Difficult to say from scratch. If you could provide your application with build/run instructions - we could check on our side.

**Comment by zjin-lcf** [comment]
Does cl_debug_info decode a SYCL kernel ?

**Comment by anton-v-gorshkov** [comment]
Yes, it tries to decode SYCL kernel but for OpenCL backend only and for GPU only. DPC++ is working on top of Level Zero for GPU and on top of OpenCL for CPU currently. So if you need GPU kernel decoding - try to use ze_debug_info tool instead.
Also note that to get kernel symbols one may need to build his DPC++ application with "-gline-tables-only" flag.
