### ISSUE TITLE
how to enable ChromePerformanceTimingInStages  in L0

### ISSUE THREAD

**Issue by guizili0** [intel/pti-gpu#5]
Hi in [opencl-intercept-layer](https://github.com/intel/opencl-intercept-layer), I can use the config ChromePerformanceTimingInStages   to dump the the multi-kernel submitted, execution time in pipeline, how to enable this one L0 trace?
Detail in: https://github.com/intel/opencl-intercept-layer/blob/master/docs/chrome_tracing.md

**Comment by anton-v-gorshkov** [comment]
Hi, right now ze_tracer does not support stages highlighting like [opencl-intercept-layer](https://github.com/intel/opencl-intercept-layer). But you can collect Chrome trace that includes both host and device activities with `--chrome-call-logging` and `--chrome-device-timeline` flags, where each kernel execution has it's unique ID that can be matched with host API calls.

E.g. one may find `zeCommandListAppendLaunchKernel` call (append phase), `zeCommandQueueExecuteCommandLists` call (submit phase), and kernel execution (execution phase) with the same ID to retrieve similar information.

If you need exactly the same functionality as ChromePerformanceTimingInStages provides - yes, I believe we can do this as well, just let us know. But note that L0 works differently than OpenCL and has not quite the same stages.

**Comment by guizili0** [comment]
I think the ChromePerformanceTimingInStages  is very helpful in performance analysis, it is great if your team can support this one.

**Comment by anton-v-gorshkov** [comment]
Got it, we will start work on this capability. Will update you when it will be ready.

**Comment by guizili0** [comment]
great, thank you!!!

**Comment by anton-v-gorshkov** [comment]
Done, `--chrome-device-stages` option. Please try it and let me know if there are any issues with this new feature.

**Comment by guizili0** [comment]
@anton-v-gorshkov  thank you for the quick response, I will check it. And close this issue now. Thanks.
