### ISSUE TITLE
Run into Segmentation fault when using unitrace for python script

### ISSUE THREAD

**Issue by Wanzizhu** [intel/pti-gpu#50]
Problem: Run into Segmentation fault when using unitrace for python script

<img width="1498" alt="image" src="https://github.com/intel/pti-gpu/assets/57359799/d17c1a02-eafd-4f2c-b290-392640bc4ded">

How to reproduce:
1. install intel_extension_for_pytorch, here is the whl link: https://ubit-artifactory-sh.intel.com/artifactory/aipc_releases-sh-local/gpu-new/releases/2024.0/IPEX_2.1.10+xpu/RC1/py310/, run `pip install ./*.whl`
2. git clone https://github.com/intel-innersource/frameworks.ai.pytorch.ipex-gpu.git
3. unitrace -d pytest tests/gpu/examples/test_pad.py

**Comment by zma2** [comment]
@Wanzizhu, can you please try the latest source? We just pushed an update.

**Comment by Wanzizhu** [comment]
Hi, i have tried latest unitrace(2.0.1 (9ee0e46cafa145856eaeeefe5f26ec046462300f)), and found this issue is gone(below is the version i used). Thanks for your update, i will close this issue.
