### ISSUE TITLE
There was a 4~5% variance in the capture results after using the "verbose" parameter.

### ISSUE THREAD

**Issue by ZePan110** [intel/pti-gpu#55]
![Snipaste_2024-01-15_11-01-03](https://github.com/intel/pti-gpu/assets/97863672/344974cd-77c8-4b9a-a560-36dbe082eed7)

with "verbose" log:
https://osgc-sh-earth1.sh.intel.com/xebot/log/PVC/tensorflow/00049489_aicontainer/hotfix_agama-ci-devel-736.9/AI.TF.Bert_large.Inference.Fp16.bs64.s.Debug/0_AI.TF.Bert_large.Inference.Fp16.bs64.s.Debug.txt
with no "verbose" log: 
https://osgc-sh-earth1.sh.intel.com/xebot/log/PVC/tensorflow/00049427_aicontainer/hotfix_agama-ci-devel-736.9/AI.TF.Bert_large.Inference.Fp16.bs64.s.Debug/0_AI.TF.Bert_large.Inference.Fp16.bs64.s.Debug.txt

**Comment by ZePan110** [comment]
test command: 
with "verbose" log:
https://osgc-sh-earth1.sh.intel.com/xebot/log/PVC/tensorflow/00049489_aicontainer/hotfix_agama-ci-devel-736.9/AI.TF.Bert_large.Inference.Fp16.bs64.s.Debug/0_AI.TF.Bert_large.Inference.Fp16.bs64.s.Debug.sh
with no "verbose" log:
https://osgc-sh-earth1.sh.intel.com/xebot/log/PVC/tensorflow/00049427_aicontainer/hotfix_agama-ci-devel-736.9/AI.TF.Bert_large.Inference.Fp16.bs64.s.Debug/0_AI.TF.Bert_large.Inference.Fp16.bs64.s.Debug.sh

**Comment by Sarbojit2019** [comment]
With 'Verbose' option on it is expected to loose the performance. It is hard to draw a line though.

**Comment by Sarbojit2019** [comment]
@ZePan110, Can you please close this ticket?

**Comment by ZePan110** [comment]
OK
