### ISSUE TITLE
Need more details on "Chrome Device Stages"

### ISSUE THREAD

**Issue by GHGmc2** [intel/pti-gpu#8]
[ze_tracer](https://github.com/intel/pti-gpu/tree/master/tools/ze_tracer)
> Chrome Device Stages mode provides alternative view for device queue where each kernel invocation is divided into stages: "appended", "submitted" and "execution".

What's the meaning of "appended" state? It means command groups are in the queue? or command groups had been submitted to compute command streamer, but command streamer has not submitted them to the engine?
The same to "submitted" state.

Thanks!

**Comment by anton-v-gorshkov** [comment]
Hi @GHGmc2,
**appended state** means kernel was added into the command list (e.g. on `zeCommandListAppendLaunchKernel `call),
**submitted state**  means command list was added into the device queue (e.g. on `zeCommandQueueExecuteCommandLists` call).
In case of immediate command list, append and submit time will be equal.

**Comment by GHGmc2** [comment]
@anton-v-gorshkov, Thanks for the explanation. But is command list SYCL queue? and device queue is command streamer in the hardware?

**Comment by anton-v-gorshkov** [comment]
Yes, I believe it's good enough explanation.

**Comment by GHGmc2** [comment]
Got it, thanks!
