### ISSUE TITLE
Add suport for `intel_get_dual_subslice_id`

### ISSUE THREAD

**Issue by TApplencourt** [intel/pti-gpu#9]
Hi Anton,

Maybe you already know, but IGC just added support for `intel_get_dual_subslice_id` (https://github.com/intel/intel-graphics-compiler/commit/cc63edd997606f0b32c5f1648d047e1461821bba). You may want to update `cl_gemm_inst` and co at some point.

If you are short on time, I can submit a PR.

Thanks again for this repo! 

Regards,
Thomas

**Comment by anton-v-gorshkov** [comment]
Thanks, Thomas!
I'll definitely add this, just need to wait for official IGC and compute-runtime releases to keep things testable. It will probably take like a week or two (current IGC [release](https://github.com/intel/intel-graphics-compiler/releases/tag/igc-1.0.7862) is based on 16 days last [commit](https://github.com/intel/intel-graphics-compiler/commit/f91868690066cb76955f00e1168a8bdd1fd62672)). Will notify you when it will be done.

**Comment by anton-v-gorshkov** [comment]
Added in version 0.32.0

**Comment by TApplencourt** [comment]
Thanks a lot! My cluster is on maintenance, so I can't try it yet :( 
Maybe a stupid remark but did you forget to update the computation of "Total number of HW thread" (https://github.com/intel/pti-gpu/blob/360b835279fdb3f279221dc0143ef2593e9e3641/samples/cl_gemm_inst/main.cc#L192) with the DSS count?

**Comment by anton-v-gorshkov** [comment]
Thanks Thomas! Indeed it's a bug, fixed in newest version.
